binary_sensor:
  - platform: analog_threshold
    name: "Cooker Overcurrent_1"
    sensor_id: cooker_current
    threshold: 30
    filters:
      - delayed_on: 10s
    on_press:
      - script.execute: beep
    on_state:
      - lvgl.label.update:
          id: current_1_value
          state:
            checked: !lambda return x;

sensor:
  - platform: homeassistant
    id: outside_temp
    entity_id: sensor.st_00141258_temperature
    on_value:
      then:
        - lvgl.label.update:
            id: out_temp_value
            text:
              format: "%.1f"
              args: [x]
  - platform: homeassistant
    entity_id: sensor.cooker_current
    id: cooker_current
    on_value:
      if:
        condition:
          lambda: "return isnan(x);"
        then:
          lvgl.label.update:
            id: current_1_value
            state:
              checked: false
            text: "--"
        else:
          - lvgl.label.update:
              id: current_1_value
              state:
                checked: !lambda return x > 30;
              text:
                format: "%.0f"
                args: [x]
          - if:
              condition:
                lambda: return x > 2;
              then:
                script.execute: light_on


  - platform: homeassistant
    id: ambient_light_ratio
    entity_id: sensor.st_00141258_illuminance
    filters:
      - lambda: return std::log10(x)/5.0;
      - clamp:
          min_value: 0.2
          max_value: 1.0

    on_value:
      then:
        - light.turn_on:
            id: display_backlight
            brightness: !lambda return x;


