#-------------------------------------------
# Waveshare ESP32-S3 Touch LCD 4" hardware configuration file

esphome:
  name: "${name}"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    advanced:
      execute_from_psram: true

preferences:
  flash_write_interval: 1min

psram:
  mode: octal
  speed: 80MHz

logger:

api:
  reboot_timeout: 0s
  on_client_connected:
    - lvgl.widget.hide: boot_screen

i2c:
  - id: tp_i2c
    sda: 15
    scl: 7
    scan: true
    frequency: 400kHz

sensor:
  - platform: htu21d
    model: htu21d
    update_interval: 5s
    temperature:
      id: temperature_id
      name: "Temperature"
    humidity:
      id: humidity_id
      name: "Humidity"
      on_value:
        - lvgl.label.update:
            id: humidity_value
            text:
              format: "%.0f"
              args: [x]
    heater:
      id: heater_id
      name: "Heater"

  - platform: copy
    source_id: humidity_id
    id: average_humidity
    name: Average Humidity
    filters:
      - exponential_moving_average:
          alpha: .00069
          send_every: 6

binary_sensor:
  - platform: analog_threshold
    sensor_id: humidity_id
    id: is_humid
    name: High Humidity
    threshold:
      upper: !lambda |-
        return id(average_humidity).state + 10.0;
      lower: !lambda |-
        return id(average_humidity).state + 7.0;
    

pca9554:
  id: expander

touchscreen:
  platform: gt911
  i2c_id: tp_i2c
  id: my_touchscreen
  reset_pin:
    pca9554: expander
    number: 0
  interrupt_pin: 16
  transform:
    swap_xy: true
    mirror_y: false
    mirror_x: true


light:
  - platform: monochromatic
    output: backlight_output
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 4s
    gamma_correct: 1.8

switch:
  - platform: gpio
    id: buzzer
    pin:
      pca9554: expander
      number: 5
      mode:
        output: true

output:
  - platform: ledc
    id: backlight_output
    pin: 44
    frequency: 1220Hz
    inverted: true
    min_power: 15%

spi:
  - id: lcd_spi
    clk_pin: GPIO2
    mosi_pin: GPIO1
    
external_components:
  - source: github://pr#9892
    components: [mipi, mipi_rgb]
    refresh: 1h

display:
  platform: mipi_rgb
  model: "WAVESHARE-4-480x480"
  rotation: 270
